SCREEN_SIZE = (800, 600)
BG_COLOR = (80, 150, 80)
SPEED = 2
FPS = 60                # 刷新率
STEP = 100
PLAYER_SHOT_LIMIT = 3   # 最多子弹数
COMPUTER_TANK = 5       # 敌方坦克数
TOTAL_COMPUTER_TANK = 20    # 总共坦克数量
PLAYER_LIFE = 3         # 玩家生命
PANELWIDTH = 50
WALL_LIFE = 3           # 墙的生命
START_MUSIC = "res/voice/start.wav" # 背景音乐
FIRE_MUSIC = "res/voice/fire.wav"   # 开火声音
